// Auto-generated by image_to_console.py from: btn2.png
// Sprite size: 15 cols x 3 rows  (each pixel = 2 console chars wide)
// Transparent pixels use color index 15 (White = background)
#pragma once

const int BTN_HOVER_W = 15;
const int BTN_HOVER_H = 3;
// Color index map (Windows Console 16 colors):
//  0=Black 1=DkBlue 2=DkGreen 3=DkCyan 4=DkRed 5=DkMagenta
//  6=Olive  7=LtGray 8=DkGray  9=Blue  10=Green  11=Cyan
// 12=Red   13=Magenta 14=Yellow 15=White(transparent)
const int BTN_HOVER[3][15] = {
    {6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 14},
    {6, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 14},
    {14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14}
};
