"""
image_to_console.py (Phiên bản RGB 24-bit True Color)
Cách dùng:
  python image_to_console.py <input_image> <output_varname> [width] [height]
Ví dụ:
  python image_to_console.py bg.png BG_AYAKA 60 40
"""

import sys
import os
from PIL import Image

def image_to_rgb_array(image_path, width, height):
    img = Image.open(image_path).convert('RGB')
    img = img.resize((width, height), Image.Resampling.NEAREST)    
    pixels = []
    for y in range(height):
        row = []
        for x in range(width):
            r, g, b = img.getpixel((x, y))
            row.append((r, g, b))
        pixels.append(row)
    return pixels

def preview_in_terminal(pixels, width, height):
    print("--- PREVIEW ---")
    for row in pixels:
        line = ""
        for (r, g, b) in row:
            # Dùng ANSI escape code để in màu nền RGB ra terminal python
            line += f"\033[48;2;{r};{g};{b}m  "
        line += "\033[0m" # Reset màu
        print(line)
    print("--- END PREVIEW ---\n")

def generate_header(pixels, var_name, width, height):
    lines = []
    lines.append("// Auto-generated by image_to_console.py (RGB Version)")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"const int {var_name}_W = {width};")
    lines.append(f"const int {var_name}_H = {height};")
    lines.append(f"// Mảng 3D chứa mã màu [Dòng][Cột][3] (0: R, 1: G, 2: B)")
    lines.append(f"const int {var_name}[{height}][{width}][3] = {{")
    
    for row in pixels:
        # Format từng dòng pixel: { {r, g, b}, {r, g, b}, ... }
        row_str = "    { " + ", ".join([f"{{{r}, {g}, {b}}}" for r, g, b in row]) + " },"
        lines.append(row_str)
        
    lines.append("};")
    return "\n".join(lines)

def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    image_path = sys.argv[1]
    var_name   = sys.argv[2].upper()
    width      = int(sys.argv[3]) if len(sys.argv) > 3 else 60
    height     = int(sys.argv[4]) if len(sys.argv) > 4 else 40

    if not os.path.exists(image_path):
        print(f"[ERROR] File not found: {image_path}")
        sys.exit(1)

    pixels = image_to_rgb_array(image_path, width, height)
    preview_in_terminal(pixels, width, height)

    header_content = generate_header(pixels, var_name, width, height)
    out_filename = f"{var_name.lower()}.h"
    with open(out_filename, "w", encoding="utf-8") as f:
        f.write(header_content)
        
    print(f"[SUCCESS] Đã tạo file: {out_filename}")

if __name__ == "__main__":
    main()